### ISSUE TITLE
Crash when rendering fluid

### ISSUE THREAD

**Issue by Andrews54757** [glisco03/isometric-renders#33]
[crash-2022-07-01_23.37.21-client.txt](https://github.com/gliscowo/isometric-renders/files/9032369/crash-2022-07-01_23.37.21-client.txt)
```
java.lang.NullPointerException: Cannot read field "field_21652" because "â˜ƒ" is null
	at net.minecraft.class_1162.method_22674(class_1162.java:125)
	at net.minecraft.class_4588.method_22918(class_4588.java:125)
	at com.glisco.worldmesher.renderers.WorldMesherFluidRenderer.method_23072(WorldMesherFluidRenderer.java:21)
	at net.minecraft.class_775.method_3347(class_775.java:179)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:85)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:593)
	at net.minecraft.class_775.handler$cei000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:85)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:593)
	at net.minecraft.class_775.handler$cei000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.minecraft.class_776.method_3352(class_776.java:76)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:509)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846.method_22757(class_846.java:132)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2305)
	at net.minecraft.class_846.method_22763(class_846.java:132)
	at net.minecraft.class_846.method_23618(class_846.java:147)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by gliscowo** [comment]
You're running an extremely outdated version of Isometric Renders that is way past its support lifetime. This crash is known and was fixed at some point, although I don't quite remember whether specifically 1.17.1 has a version where this does not happen. The only advice I can give you is to update Isometric Renders to the latest version available - I simple don't have the time to support and fix builds from a year ago
Cheers

**Comment by machiecodes** [comment]
AKA: Cope
