### ISSUE TITLE
unable to batch render tags

### ISSUE THREAD

**Issue by brecert** [glisco03/isometric-renders#37]
This seems to happen whether items or blocks are specified no matter what.

I'm on Windows.

`/isorender tag #minecraft:beds batch items`

```
[10:01:06] [Render thread/WARN]: Error while executing client-sided command '/isorender tag #minecraft:beds batch items'
java.nio.file.InvalidPathException: Illegal char <:> at index 21: batches/tag_minecraft:beds/items/
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
	at java.nio.file.Path.resolve(Unknown Source) ~[?:?]
	at com.glisco.isometricrenders.render.BatchRenderable.<init>(BatchRenderable.java:35) ~[isometric-renders-0.3.1+1.18.jar:?]
	at com.glisco.isometricrenders.render.BatchRenderable.of(BatchRenderable.java:45) ~[isometric-renders-0.3.1+1.18.jar:?]
	at com.glisco.isometricrenders.render.RenderTask.lambda$static$1(RenderTask.java:20) ~[isometric-renders-0.3.1+1.18.jar:?]
	at com.glisco.isometricrenders.command.IsorenderCommand.renderTagContents(IsorenderCommand.java:124) ~[isometric-renders-0.3.1+1.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142) ~[brigadier-1.0.18.jar:?]
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:89) ~[fabric-command-api-v1-1.1.9+d7c144a860-e25e6711fa98433e.jar:?]
	at net.minecraft.class_746.handler$zgi000$onSendChatMessage(class_746.java:2304) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_3142(class_746.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25425(class_437.java:378) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25427(class_437.java:371) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25404(class_408.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:384) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:380) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:472) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:472) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) [lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) [lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1147) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
[10:01:06] [Render thread/INFO]: [CHAT] Illegal char <:> at index 21: batches/tag_minecraft:beds/items/
```

**Comment by gliscowo** [comment]
Fixed by #40, should be in a release soon
Cheers
